package pvt.arjunasdk.enums;

public enum BatteriesPropertyType {
	CONFIG_CENTRAL_FILE_NAME, 
	CONFIG_PROJECT_FILE_NAME, 
	TOOLS_DIR, 
	PROJECT_LOG_DIR, 
	CONFIG_DIR,
	PROJECT_CONFIG_DIR,
	PROJECT_TEMP_DIR, 
	PROJECT_DATA_DIR, 
	PROJECT_DATA_SOURCES_DIR, 
	PROJECT_DATA_REFERENCES_DIR, 
	PROJECT_SCREENSHOTS_DIR, 
	LOGGING_CONSOLE_ON, 
	LOGGING_CONSOLE_LEVEL, 
	LOGGING_FILE_ON, 
	LOGGING_FILE_LEVEL, 
	LOGGING_NAME,
	DIRECTORY_ROOT,
	PROJECT_DIR
}
