package pvt.arjunapro.enums;

public enum BatteriesPropertyType {
	CONFIG_CENTRAL_FILE_NAME, 
	CONFIG_PROJECT_FILE_NAME, 
	DIRECTORY_TOOLS_ROOT, 
	DIRECTORY_PROJECT_LOG, 
	DIRECTORY_CONFIG,
	DIRECTORY_PROJECT_CONFIG,
	DIRECTORY_PROJECT_TEMP, 
	DIRECTORY_PROJECT_DATA_ROOT, 
	DIRECTORY_PROJECT_DATA_SOURCES, 
	DIRECTORY_PROJECT_DATA_REFERENCES, 
	DIRECTORY_PROJECT_SCREENSHOTS, 
	LOGGING_CONSOLE_ON, 
	LOGGING_CONSOLE_LEVEL, 
	LOGGING_FILE_ON, 
	LOGGING_FILE_LEVEL, 
	LOGGING_NAME,
	DIRECTORY_ROOT,
	DIRECTORY_PROJECT_ROOT
}
