package com.autocognite.arjuna.enums;

public enum ValueType {
	BOOLEAN, STRING, STRING_LIST, NULL, NUMBER, NUMBER_LIST, LIST, ANYREF, ENUM, ENUM_LIST, INTEGER, ANYREF_LIST, FLOAT, DOUBLE, LONG, NOT_SET, NA
}
