package com.autocognite.pvt.batteries.enums;

public enum BatteriesPropertyType {
	CONFIG_FILE_NAME, 
	DIRECTORY_TOOLS_ROOT, 
	DIRECTORY_LOG, 
	DIRECTORY_CONFIG, 
	DIRECTORY_TEMP, 
	DIRECTORY_DATA_ROOT, 
	DIRECTORY_DATA_SOURCES, 
	DIRECTORY_DATA_REFERENCES, 
	DIRECTORY_SCREENSHOTS, 
	LOGGING_CONSOLE_ON, 
	LOGGING_CONSOLE_LEVEL, 
	LOGGING_FILE_ON, 
	LOGGING_FILE_LEVEL, 
	LOGGING_FILE_NAME,
	DIRECTORY_ROOT,
	DIRECTORY_PROJECT
}
