package com.autocognite.pvt.arjuna.enums;

public enum IssueSubType {
	FIXTURE_SETUP_SESSION,
	FIXTURE_SETUP_GROUP,
	FIXTURE_SETUP_CLASS,
	FIXTURE_SETUP_CLASS_FRAGMENT,
	FIXTURE_TEARDOWN_SESSION,
	FIXTURE_TEARDOWN_GROUP,
	FIXTURE_TEARDOWN_CLASS,
	FIXTURE_TEARDOWN_CLASS_FRAGMENT,
	FIXTURE_SETUP_METHOD,
	FIXTURE_TEARDOWN_METHOD,
	FIXTURE_SETUP_TEST,
	FIXTURE_TEARDOWN_TEST,
	CONSTRUCTOR,
	STEP_FAILURE,
	STEP_ERROR
}
