package pvt.arjunapro.enums;

public enum TestPickerProperty {
	PACKAGE_NAME,
	CLASS_NAME,
	PACKAGE_CONSIDER_PATTERNS,
	PACKAGE_IGNORE_PATTERNS,
	CLASS_CONSIDER_PATTERNS,
	CLASS_IGNORE_PATTERNS,
	METHOD_CONSIDER_PATTERNS,
	METHOD_IGNORE_PATTERNS,
	FILTER_PACKAGES_ON,
	FILTER_CLASSES_ON,
	FILTER_METHODS_ON
}
